#
# This is a Shiny web application. You can run the application by clicking
# the 'Run App' button above.

library(shiny)
library(shinyjs)
library(shinyBS)
library(filterNHP)
library(rclipboard)

primates <- readRDS("www/primte_taxa.rds")
taxa_options <- sort(as.vector(unlist(primates)))

# ui ----------------------------------------------------------------------

ui <-
  fluidPage(
    shinyjs::useShinyjs(),
    rclipboardSetup(),
    includeCSS("www/style.css"),
    style = "font-size: 15px;",
    titlePanel(
      title = div(
        a(img(src = 'packageHex_v2_20210121.png',
              height = '75px', width = '75px'),
          href="https://github.com/avrincon/filterNHP"),
        "filterNHP: Non-human primate (NHP) search filter generator"
      ),
      windowTitle = "filterNHP: Non-human primate (NHP) search filter generator"
    ),

    h5("version 0.0.1"),

    tabsetPanel(
      tabPanel(
        title = "App",

        flowLayout(
          cellArgs = list(
            # id = "instruction_inputs",
            style = "min-width:650px;
                     word-wrap:break-word"
          ),
          wellPanel(
            id = "instruction_well",
            fluidRow(
              p("Identifying all of the relevant research on a particular topic for literature reviews involving non-human primates (NHPs) can be difficult and time consuming. filterNHP automatizes the creation of search filters for the taxonomic levels of NHPs for three bibliographic databases (",
                a("PubMed",
                  href = "https://pubmed.ncbi.nlm.nih.gov/",
                  .noWS = "outside"),
                ", ",
                a("PsycINFO",
                  href = "http://search.ebscohost.com/Login.aspx?profile=web&defaultdb=psyh&lp=login.asp&ref=https%3A%2F%2Fwww%2Egoogle%2Ecom%2F&authtype=ip,uid",
                  .noWS = "outside"),
                ", and ",
                a("Web of Science",
                  href = "http://login.webofknowledge.com/error/Error?Error=IPError&PathInfo=%2F&RouterURL=http%3A%2F%2Fwww.webofknowledge.com%2F&Domain=.webofknowledge.com&Src=IP&Alias=WOK5",
                  .noWS = "outside"),
                ").",
                "These search filters can be combined with topic search strings using the Boolean operator 'AND' to facilitate the retrieval of all publications related to NHPs and the topic within the specified database."
                # style="min-width:1000px; word-wrap:break-word;"
              )
            ),
            fluidRow(
              p(
                em("Usage:"),
                br(),
                tags$ul(
                  tags$li("Select the database of interest."),
                  tags$li('Determine the broadest taxonomic level(s) of NHP desired (see primate order table) and select option(s) from "Taxa to include" in the panel to the right.',
                          tags$ul(
                            tags$li('If a search filter for all non-human primates is desired, simply tick the checkbox.'),
                            tags$li('Exclusion of a sub-group can be specified by selecting from "Taxa to exclude".')
                          )
                  ),
                  tags$li('Hit "Create!"'),
                  tags$li('Copy and paste the generated search filter into the corresponding database.')
                )
              )
            ),
            fluidRow(
              p("filterNHP is a dynamic application and taxonomy changes frequently. Therefore, we encourage you (the app user) to review the search filters generated by filterNHP and adapt them to your own needs. For further details, please refer to our publication: Cassidy et al.,", em("in review", .noWS = "after"), ".")
            )
          ),

          wellPanel(
            id = "input_well",
            selectInput(
              inputId = "database_input",
              label = "Database",
              choices = c("PubMed", "PsycINFO", "Web of Science"),
              selected = "PubMed"
            ),

            selectInput("include_text",
                        label = "Taxa to include",
                        choices = taxa_options,
                        multiple = TRUE),
            shinyBS::bsTooltip(
              id = "include_text",
              title = "Type to filter options"
            ),

            checkboxGroupInput(
              inputId = "all_nhp_input",
              label = NULL,
              choiceNames = c("All non-human primates"),
              choiceValues = c("nonhuman_primates"),
            ),
            shinyBS::bsPopover(
              id = "all_nhp_input",
              title = "Create search filter for all non-human primates"
            ),

            selectInput("exclude_text",
                        label = "Taxa to exclude",
                        choices = taxa_options,
                        multiple = TRUE),
            shinyBS::bsTooltip(
              id = "exclude_text",
              title = "Type to filter options"
            ),

            actionButton(inputId = "create", "Create!"),
            actionButton(inputId = "clear_button", "Clear", icon("eraser")),

            br(),
            br(),

            p("Please cite: Cassidy LC, Leenaars CHC, Rincon AV, Pfefferle D,",
              '(', em("in review", .noWS = c("outside")), ').',
              '"Comprehensive search filters for retrieving publications on non-human primates for literature reviews (filterNHP)".',
              em('American Journal of Primatology', .noWS = c("after")),
              '.')
          )
        ),

        div(
          h3(
            p("Search Filter",
              uiOutput(outputId = "clip", inline = TRUE)
            )
          ),
          h4("Copy search filter and paste in relevant database"),
          div(
            # id = "search_filter",
            textOutput(outputId = "search_filter")
          )
        ),

        div(
          h3(
            "Primate order",
            actionButton(inputId = "table_button",
                         label = "",
                         icon = icon("chevron-up"))
          ),
          div(
            id = 'primate_order_div',
            includeHTML("www/primate-order-table.html")
          )
        ),
      ),

# FAQ panel ---------------------------------------------------------------

      tabPanel(
        title = "FAQ",
        # h1("Frequently Asked Questions"),
        h3("Why is the search filter syntax different for each database?",
           class = "faq_head",
           actionButton(inputId = "faq1_button",
                        label = "",
                        icon = icon("chevron-down"))),
        hidden(
          div(class = "faq", id = "faq1_answer",
              includeHTML("www/FAQ-1.html")
          )
        ),

        h3("What are index terms?",
           class = "faq_head",
           actionButton(inputId = "faq2_button",
                        label = "",
                        icon = icon("chevron-down"))),
        hidden(
          div(class = "faq", id = "faq2_answer",
              includeHTML("www/FAQ-2.html")
          )
        ),

        h3("Why do I detect publications that are not related to NHPs?",
           class = "faq_head",
           actionButton(inputId = "faq3_button",
                        label = "",
                        icon = icon("chevron-down"))),
        hidden(
          div(class = "faq", id = "faq3_answer",
              includeHTML("www/FAQ-3.html")
          )
        )
      ),

# revision history --------------------------------------------------------

      tabPanel(
        title = "Version History",
        h4("version 0.0.1"),
        p("Initial release.")
      )
    )
  )


# server ------------------------------------------------------------------


server <- function(input, output, session) {

  # Add clipboard button so it is visible on launch, copy blank
  output$clip <- renderUI({
    rclipButton(inputId = "clip_button", label = "Copy",
                clipText = "",
                icon("clipboard"))
  })

  # deselect all_nhp_input input if any text is added to include_text input
  # cannot use reactive_taxa() in here (not sure why)
  observe({
    x <- c(input$include_text)

    # Can use character(0) to remove all choices
    if (!is.null(x))
      x <- character(0)

    # Untick all NHP if another taxa is selected
    updateCheckboxGroupInput(session, inputId = "all_nhp_input",
                             label = NULL,
                             choiceNames = c("All non-human primates"),
                             choiceValues = c("nonhuman_primates"),
                             selected = x
    )
  })

  # create reactive vector of taxa input for filter_nhp()
  # will only create search filter when button is clicked
  # takes the input from the text boxes
  # if include text box is empty, it will take input from all nhp checkbox
  v <- reactiveValues(taxa = NULL,
                      exclude = NULL)

  observeEvent(input$create, {

    if (length(input$include_text) > 0){
      v$taxa <- input$include_text
    }
    if (length(input$include_text) == 0){
      v$taxa <- input$all_nhp_input
    }
    if (length(input$exclude_text) > 0){
      v$exclude <- input$exclude_text
    }

    # create search filter to copy
    res <-
      filter_nhp(database = input$database_input,
                 taxa = v$taxa,
                 exclude = v$exclude,
                 simplify = FALSE)

    # copy search filter to clipboard
    output$clip <- renderUI({
      rclipButton(inputId = "clip_button", label = "Copy",
                  clipText = res,
                  icon("clipboard"))
    })
  })

  # print search filter to screen
  output$search_filter <-
    renderPrint(
      filter_nhp(
        database = input$database_input,
        taxa = v$taxa,
        exclude = v$exclude
      )
    )

  # clear text boxes and search filter
  observeEvent(input$clear_button, {
    updateTextInput(session,
                    inputId = "include_text",
                    value = "")
    updateTextInput(session,
                    inputId = "exclude_text",
                    value = "")
    v$taxa <- NULL
    v$exclude <- NULL

    # clear clipboard
    output$clip <- renderUI({
      rclipButton(inputId = "clip_button", label = "Copy",
                  clipText = " ",
                  icon("clipboard"))
    })
  })

  # hide/show primate table after clicking button
  # toggle icon arrows for show/hide
  observeEvent(input$table_button, {
    toggle('primate_order_div')
    if(input$table_button %% 2 == 1){
      updateActionButton(session,
                         inputId = "table_button",
                         icon = icon("chevron-down"))
    }else{
      updateActionButton(session,
                         inputId = "table_button",
                         icon = icon("chevron-up"))
    }
  })
  observeEvent(input$faq1_button, {
    toggle('faq1_answer')
    if(input$faq1_button %% 2 == 1){
      updateActionButton(session,
                         inputId = "faq1_button",
                         icon = icon("chevron-up"))
    }else{
      updateActionButton(session,
                         inputId = "faq1_button",
                         icon = icon("chevron-down"))
    }
  })
  observeEvent(input$faq2_button, {
    toggle('faq2_answer')
    if(input$faq2_button %% 2 == 1){
      updateActionButton(session,
                         inputId = "faq2_button",
                         icon = icon("chevron-up"))
    }else{
      updateActionButton(session,
                         inputId = "faq2_button",
                         icon = icon("chevron-down"))
    }
  })
  observeEvent(input$faq3_button, {
    toggle('faq3_answer')
    if(input$faq3_button %% 2 == 1){
      updateActionButton(session,
                         inputId = "faq3_button",
                         icon = icon("chevron-up"))
    }else{
      updateActionButton(session,
                         inputId = "faq3_button",
                         icon = icon("chevron-down"))
    }
  })

}

# Run the application
shinyApp(ui = ui, server = server)
