#
# This is a Shiny web application. You can run the application by clicking
# the 'Run App' button above.

library(shiny)
library(shinyjs)
library(shinyWidgets)
# library(kableExtra)
library(filterNHP)
# library(clipr)


primates <- readRDS("www/primte_taxa.rds")
d <- read.delim("www/primate_tree_kable.txt")

# ui ----------------------------------------------------------------------


ui <-
  fluidPage(
    useShinyjs(),
    titlePanel("filterNHP: Non-human primate (NHP) search filter generator"),

    wellPanel(
      fluidRow(
        column(
          width = 12,
          p("Identifying all of the relevant research on a particular topic involving non-human primates (NHPs) can be difficult and time consuming. Therefore, we created filterNHP to aid researchers in their literature reviews and save precious time. filterNHP automatizes the creation of search filters for the taxonomic levels of NHPs for three bibliographic databases (PubMed, PsycINFO, and Web of Science) using their specific syntax and index terms. These search filters can be combined with topic search strings using the Boolean operator 'AND' to facilitate the retrieval of all publications related to NHPs and the topic within the specified database.",
            style="max-width:1000px; word-wrap:break-word;"
          )
        )
      ),
      fluidRow(
        column(
          width = 12,
          p(
            em("Usage:"),
            br(),
            'Determine database of interest and the broadest taxonomic level(s) of NHP desired (see Primate order button), select in the filter panel, and hit "Create"! filterNHP will generate a search filter for the desired taxonomic level, which can easily be copied and pasted into the corresponding database.',
            br(),
            'Please note that if exclusion of a particular sub-group within a taxonomic level is desired, the user must first specify the broadest taxonomic level, hit "Add", then specify the excluded sub-group and hit "Exclude" followed by "Create".',
            style="max-width:1000px; word-wrap:break-word;"
          )
        )
      )
    ),


    sidebarPanel(
      "Select taxonomic group and database",

      br(),
      br(),

      selectInput(
        inputId = "database_input",
        label = "Database",
        choices = c("PubMed", "PsycINFO", "Web of Science"),
        selected = "PubMed"
      ),
      checkboxGroupInput(
        inputId = "all_nhp_input",
        label = NULL,
        choiceNames = c("All non-human primates"),
        choiceValues = c("nonhuman_primates")
        # selected = "nonhuman_primates"
      ),
      pickerInput(
        inputId = "suborder_input",
        label = "Suborder",
        choices = primates$suborder,
        multiple = TRUE,
        options = pickerOptions(actionsBox = TRUE)
      ),
      pickerInput(
        inputId = "infraorder_input",
        label = "Infraorder",
        choices = primates$infraorder,
        multiple = TRUE,
        options = pickerOptions(actionsBox = TRUE)
      ),
      pickerInput(
        inputId = "parvorder_input",
        label = "Parvorder",
        choices = primates$parvorder,
        multiple = TRUE,
        options = pickerOptions(actionsBox = TRUE)
      ),
      pickerInput(
        inputId = "superfamily_input",
        label = "Superfamily",
        choices = primates$superfamily,
        multiple = TRUE,
        options = pickerOptions(actionsBox = TRUE)
      ),
      pickerInput(
        inputId = "family_input",
        label = "Family",
        choices = primates$family,
        multiple = TRUE,
        options = pickerOptions(actionsBox = TRUE)
      ),
      pickerInput(
        inputId = "subfamily_input",
        label = "Subfamily",
        choices = primates$subfamily,
        multiple = TRUE,
        options = pickerOptions(actionsBox = TRUE)
      ),
      pickerInput(
        inputId = "tribe_input",
        label = "Tribe",
        choices = primates$tribe,
        multiple = TRUE,
        options = pickerOptions(actionsBox = TRUE),
      ),
      pickerInput(
        inputId = "genus_input",
        label = "Genus",
        choices = primates$genus,
        multiple = TRUE,
        options = pickerOptions(actionsBox = TRUE)
      ),
      br(),
      actionButton(inputId = "include_button", "Add to include"),
      actionButton(inputId = "exclude_button", "Add to exclude"),
      br(),
      br(),


      p(
        "Please cite the following publication when using search filters generated by filterNHP:",
        br(),
        'Cassidy LC, Leenaars CHC, Rincon AV, Pfefferle D, (2020). "Comprehensive search filters for retrieving publications on non-human primates for literature reviews (filterNHP)".',
        em('American Journal of Primatology', .noWS = c("after")),
        ', vol(iss): page #s. doi: XXXX (Google scholar link)'
      )


    ),


    mainPanel(
      "Copy search filter and paste in relevant database",

      br(),
      br(),

      fluidRow(
        tags$a(img(src = 'packageHex_20201015.png',
                   height = '150x', width = '150px',
                   style = "float:right"),
               href="https://github.com/avrincon/filterNHP"),
        img(src = 'sw_sketch.png', height = '294px', width = '434px'),
      ),
      # img(src = 'Table_2_primate_order.png', height = '645px', width = '1080px'),
      br(),
      br(),
      textInput("include_text", label = "Taxa to include", value = ""),
      textInput("exclude_text", label = "Taxa to exclude", value = ""),
      br(),
      actionButton(inputId = "create", "Create search filter"),
      actionButton(inputId = "copy_button", "Copy search filter"),
      actionButton(inputId = "table_button", "Show primate order"),
      br(),
      textOutput(outputId = "search_terms"),
      # use hidden and div to show/hide nhp table
      hidden(
        div(id='table_div',
            uiOutput(outputId = "nhp_table")
        ))
    )
  )


# server ------------------------------------------------------------------


server <- function(input, output, session) {

  # deselect all_nhp_input input if any other level is selected
  # cannot use reactive_taxa() in here (not sure why)
  observe({
    x <- c(input$suborder_input,
           input$infraorder_input,
           input$parvorder_input,
           input$superfamily_input,
           input$family_input,
           input$subfamily_input,
           input$tribe_input,
           input$genus_input)

    # x <- reactive_taxa()

    # Can use character(0) to remove all choices
    if (!is.null(x))
      x <- character(0)

    # Untick all NHP if another taxa is selected
    updateCheckboxGroupInput(session, inputId = "all_nhp_input",
                             label = NULL,
                             choiceNames = c("All non-human primates"),
                             choiceValues = c("nonhuman_primates"),
                             selected = x
    )
  })


  # will add taxa from side pannel to include/exclude text boxes when button is clicked
  observeEvent(input$include_button,{
    updateTextInput(session,
                    inputId = 'include_text',
                    value = paste0(input$all_nhp_input,
                                   input$suborder_input,
                                   input$infraorder_input,
                                   input$parvorder_input,
                                   input$superfamily_input,
                                   input$family_input,
                                   input$subfamily_input,
                                   input$tribe_input,
                                   input$genus_input))
  })
  observeEvent(input$exclude_button,{
    updateTextInput(session,
                    inputId = 'exclude_text',
                    value = paste0(input$all_nhp_input,
                                   input$suborder_input,
                                   input$infraorder_input,
                                   input$parvorder_input,
                                   input$superfamily_input,
                                   input$family_input,
                                   input$subfamily_input,
                                   input$tribe_input,
                                   input$genus_input))
  })

  # create reactive vector of taxa input for filter_nhp()
  # will only create search filter when button is clicked
  # takes the input from the text boxes
  # if include text box is empty, it will take input from side panel
  v <- reactiveValues(taxa = NULL,
                      exclude = NULL)

  split_string <- function(string) {
    # split strings from text input by comma, space and ;
    xx <- unlist(strsplit(string, split = ",|\\s|;"))
    xx[xx!=""]
  }
  observeEvent(input$create, {

    if (nchar(input$include_text) > 0){
      v$taxa <-
        split_string(input$include_text)
    }
    if (nchar(input$include_text) == 0){
      v$taxa <- c(
        input$all_nhp_input,
        input$suborder_input,
        input$infraorder_input,
        input$parvorder_input,
        input$superfamily_input,
        input$family_input,
        input$subfamily_input,
        input$tribe_input,
        input$genus_input
      )
    }

    if (nchar(input$exclude_text) > 0){
      v$exclude <-
        split_string(input$exclude_text)
    }
    if (nchar(input$exclude_text) == 0){
      v$exclude <- NULL
    }
  })

  # print search filter
  output$search_terms <-
    renderPrint(
      filter_nhp(
        database = input$database_input,
        taxa = v$taxa,
        exclude = v$exclude
      )
    )

  # copy filter_nhp() output to clipboard
  observeEvent(input$copy_button, {
    clipr::write_clip(
      filter_nhp(database = input$database_input,
                 taxa = v$taxa,
                 exclude = v$exclude,
                 simplify = F))
  })

  # show/hide primate table after clicking button
  observeEvent(input$table_button, {
    toggle('table_div')

    output$nhp_table <- renderUI({
      imageOutput("dynamic_tbl")
    })
    output$dynamic_tbl <- renderImage({
      # Return a list containing the filename and other info
      list(src = "www/Table_2_primate_order.png",
           height = '645px', width = '1080px')
    },
    deleteFile = FALSE)
  })

}

# Run the application
shinyApp(ui = ui, server = server)
