#
# This is a Shiny web application. You can run the application by clicking
# the 'Run App' button above.

library(shiny)
library(shinyjs)
library(shinyWidgets)
# library(kableExtra)
library(filterNHP)
# library(clipr)


primates <- readRDS("www/primte_taxa.rds")
d <- read.delim("www/primate_tree_kable.txt")

# ui ----------------------------------------------------------------------


ui <-
  fluidPage(
    useShinyjs(),
    includeCSS("www/style.css"),
    titlePanel(
      title = div(
        tags$a(img(src = 'packageHex_20201015.png',
                   height = '150px', width = '150px'),
               href="https://github.com/avrincon/filterNHP"),
        "filterNHP: Non-human primate (NHP) search filter generator"
      )
    ),

    flowLayout(
      cellArgs = list(
        style = "min-width:650px;
                 word-wrap:break-word;"
      ),
      wellPanel(
        fluidRow(
          p("Identifying all of the relevant research on a particular topic involving non-human primates (NHPs) can be difficult and time consuming. Therefore, we created filterNHP to aid researchers in their literature reviews and save precious time. filterNHP automatizes the creation of search filters for the taxonomic levels of NHPs for three bibliographic databases (PubMed, PsycINFO, and Web of Science) using their specific syntax and index terms. These search filters can be combined with topic search strings using the Boolean operator 'AND' to facilitate the retrieval of all publications related to NHPs and the topic within the specified database."
            # style="min-width:1000px; word-wrap:break-word;"
          )
        ),
        fluidRow(
          p(
            em("Usage:"),
            br(),
            'Determine database of interest and the broadest taxonomic level(s) of NHP desired (see Primate order table for possible options). If a search filter for all NHPs is desired, simply tick the "all non-human primates" check box. Otherwise type in the desired taxa in the text box. It is possible to exclude a sub-group of the desired taxa by adding it to "Taxa to exlude" text box. Hit "Create"! and filterNHP will generate a search filter for the desired taxonomic level, which can be copied and pasted into the corresponding database.'
          )
        ),
        fluidRow(
          p("Please cite the following publication when using search filters generated by filterNHP:",
            br(),
            'Cassidy LC, Leenaars CHC, Rincon AV, Pfefferle D, (2020). "Comprehensive search filters for retrieving publications on non-human primates for literature reviews (filterNHP)".',
            em('American Journal of Primatology', .noWS = c("after")),
            ', vol(iss): page #s. doi: XXXX (Google scholar link)'
          )
        )

      ),

      wellPanel(
        selectInput(
          inputId = "database_input",
          label = "Database",
          choices = c("PubMed", "PsycINFO", "Web of Science"),
          selected = "PubMed"
        ),
        textInput("include_text", label = "Taxa to include", value = ""),
        checkboxGroupInput(
          inputId = "all_nhp_input",
          label = NULL,
          choiceNames = c("All non-human primates"),
          choiceValues = c("nonhuman_primates")
          # selected = "nonhuman_primates"
        ),
        textInput("exclude_text", label = "Taxa to exclude", value = ""),
        br(),
        actionButton(inputId = "create", "Create!"),
        actionButton(inputId = "copy_button", "Copy"),
        actionButton(inputId = "clear_button", "Clear")
      )
    ),

    fluidRow(
      style = "min-width:1250px;
               word-wrap:break-word;
               margin: 20px;",
      # img(src = 'sw_sketch.png', height = '294px', width = '434px')
      includeHTML("www/primate-order-table.html")
    ),


    div(strong("Filter:"),
        "Copy search filter and paste in relevant database",
        style = "margin: 10px;",
        textOutput(outputId = "search_terms")
    )
  )


# server ------------------------------------------------------------------


server <- function(input, output, session) {

  # deselect all_nhp_input input if any text is added to include_text input
  # cannot use reactive_taxa() in here (not sure why)
  observe({
    x <- c(input$include_text)

    # Can use character(0) to remove all choices
    if (!is.null(x))
      x <- character(0)

    # Untick all NHP if another taxa is selected
    updateCheckboxGroupInput(session, inputId = "all_nhp_input",
                             label = NULL,
                             choiceNames = c("All non-human primates"),
                             choiceValues = c("nonhuman_primates"),
                             selected = x
    )
  })

  # create reactive vector of taxa input for filter_nhp()
  # will only create search filter when button is clicked
  # takes the input from the text boxes
  # if include text box is empty, it will take input from all nhp checkbox
  v <- reactiveValues(taxa = NULL,
                      exclude = NULL)

  split_string <- function(string) {
    # split strings from text input by comma, space and semicolon
    xx <- unlist(strsplit(string, split = ",|\\s|;"))
    xx[xx != ""]
  }
  observeEvent(input$create, {

    if (nchar(input$include_text) > 0){
      v$taxa <-
        split_string(input$include_text)
    }
    if (nchar(input$include_text) == 0){
      v$taxa <- input$all_nhp_input
    }
    if (nchar(input$exclude_text) > 0){
      v$exclude <-
        split_string(input$exclude_text)
    }
    if (nchar(input$exclude_text) == 0){
      v$exclude <- NULL
    }
  })

  # print search filter
  output$search_terms <-
    renderPrint(
      filter_nhp(
        database = input$database_input,
        taxa = v$taxa,
        exclude = v$exclude
      )
    )

  # copy filter_nhp() output to clipboard
  observeEvent(input$copy_button, {
    clipr::write_clip(
      filter_nhp(database = input$database_input,
                 taxa = v$taxa,
                 exclude = v$exclude,
                 simplify = F))
  })

  # clear include and exclude textboxes
  observeEvent(input$clear_button, {
    updateTextInput(session,
                    inputId = "include_text",
                    value = "")
    updateTextInput(session,
                    inputId = "exclude_text",
                    value = "")
    # output$search_terms <-
    #   renderPrint("")
  })

}

# Run the application
shinyApp(ui = ui, server = server)
